version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - yum -y install unzip
      - curl -s -o /tmp/terraform.zip "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
      - unzip -o /tmp/terraform.zip -d /tmp/
      - chmod +x /tmp/terraform
      - mv /tmp/terraform /usr/local/bin/
      - rm -f /tmp/terraform.zip
      - terraform --version
    
  pre_build:
    commands:
      - echo "Starting Terraform plan phase..."
      - find . -type d -name "terraform"
      - cd terraform
      - |
        echo "AWS_REGION: $AWS_REGION"
        echo "PROJECT_NAME: $PROJECT_NAME"
        echo "ENVIRONMENT: $ENVIRONMENT"
        echo "APP_NAME: $APP_NAME"
        echo "AWS Region: $AWS_REGION"
        echo "AWS Account ID (from ARN): $(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')"
        echo "AWS Account ID (from STS): $(aws sts get-caller-identity --query "Account" --output text)"
      - account_id=$(aws sts get-caller-identity --query "Account" --output text)
      - |
        terraform init -upgrade \
        -backend-config="region=$AWS_REGION" \
        -backend-config="bucket=${account_id}-terraform-state" \
        -backend-config="key=${ENVIRONMENT}/${APP_NAME}/terraform.tfstate" \
        -backend-config="dynamodb_table=${account_id}-terraform-state-lock"
      
  build:
    commands:
      - echo "Running Terraform apply..."
      - terraform apply --var-file="../tfvars/${ENVIRONMENT}/terraform.tfvars" -auto-approve
      
  post_build:
    commands:
      - echo "Terraform apply completed on `date`"
      
